---
# tasks file for ansible-role-disable-edac
# unload all edac related modules
- name: unload edac modules
  become: yes
  modprobe:
    name: "{{ item }}"
    state: absent
  with_items: "{{ edac_modules }}"

# make sure the modprobe.d dir exists
- name: create /etc/modprobe.d dir
  become: yes
  file:
    path: /etc/modprobe.d
    state: directory
    owner: root
    group: root
    mode: 0755

# unload all edac related modules
- name: blacklist edac modules
  become: yes
  kernel_blacklist:
    name: "{{ item }}"
    state: present
  with_items: "{{ edac_modules }}"
